apiVersion: v1
kind: Service
metadata:
  name: website-external-svc
spec:
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  clusterIP: 10.96.15.6
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
